name: JuliaFormatter
on: [push, pull_request]

jobs:
  format:
    name: Format with JuliaFormatter.jl
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Setup Git configuration
      run: |
        git config --global user.name 'autoprettier'
        git config --global user.email 'actions@github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
    - name: Install Julia packages
      run: |
        echo "deb http://ppa.launchpad.net/julia-dev/stable/ubuntu $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list
    - name: Update package lists
        sudo apt-get update && sudo apt-get install julia -y
    - name: Run Julia formatting
      run: |
        julia  -e 'using Pkg; Pkg.add(PackageSpec(name="JuliaFormatter"))'
        julia  -e 'using JuliaFormatter; format(".", verbose=true)'
    - name: Commit changes and push changes
      run: |
        git diff
        git commit -am "ðŸš€ Formatting files" || true
        git push --force origin HEAD:$GITHUB_REF || true
